INSERT INTO USER ( USER_ID, USER_TOKEN, USER_NICKNAME, USER_TYPE, USER_DT )
VALUES ( 'redrabbit', 'HITIHEHIOSAKFLHAIEUKFJDH', 'REDRED', 'DJ', NOW() );

INSERT INTO USER ( USER_ID, USER_TOKEN, USER_NICKNAME, USER_TYPE, USER_DT )
VALUES ( 'BLUERABBIT', 'ASIDHFLAIUWBSVLAHI', 'BLUEBLUE', 'USER', NOW() );

INSERT INTO WAVE ( WAVE_DJ, WAVE_NAME, WAVE_DESC, WAVE_LIVE, WAVE_IMG, WAVE_VIEW, WAVE_DT )
VALUES ( 'BLACKRABBIT', 'BLACKPINK', '내심장의색깔은블랙', FALSE, '/files/img/BLACKPINK.png', 5, NOW());

INSERT INTO FILE ( WAVE_ID, FILE_NAME, FILE_LINK, FILE_DT )
VALUES ( WAVE_ID, 'FILENAME', 'FILELINK', NOW() );

INSERT INTO CHAT ( USER_ID, WAVE_ID, CHAT_COMMENT, CHAT_DT )
VALUES ( 'USER_ID', WAVE_ID, 'COMMENT', NOW() )

INSERT INTO EVENT ( WAVE_ID, FILE_ID, EVENT_TYPE, EVENT_VALUE, EVENT_TIME )
VALUES ( WAVE_ID, FILE_ID, 'TYPE', VALUE, TIME )

INSERT INTO FOLLOW ( USER_ID, FOLLOW_DJ, FOLLOW_DT )
VALUES ( 'BLUERABBIT',  'BLACKRABBIT', NOW() );

INSERT INTO SUPPORT ( USER_ID, SUPPORT_DJ, SUPPORT_DT )
VALUES ( 'BLUERABBIT', 'BLACKRABBIT', NOW() );




//live중인 wave 3개 출력
SELECT WAVE_DJ, WAVE_NAME, WAVE_DESC, WAVE_LIVE, WAVE_IMG, WAVE_VIEW, WAVE_DT
FROM WAVE
WHERE WAVE_LIVE = TRUE
LIMIT 3;

//제일 view 많은 wave 3개 출력
SELECT WAVE_DJ, WAVE_NAME, WAVE_DESC, WAVE_LIVE, WAVE_IMG, WAVE_VIEW, WAVE_DT
FROM WAVE
ORDER BY WAVE_VIEW DESC
LIMIT 3;
